spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    enabled: false
    schemas: courseplatform
    repair-on-migrate: true
    validate-on-migrate: false
    clean-on-validation-error: true
