# 健康检查测试

### 1. 检查学习微服务健康状态
GET http://localhost:8084/actuator/health

### 2. 检查用户服务健康状态
GET http://localhost:8081/actuator/health

### 3. 检查课程服务健康状态
GET http://localhost:8082/actuator/health

### 4. 检查内容服务健康状态
GET http://localhost:8083/actuator/health

### 第一步：获取有效token
POST http://localhost:8081/api/user/login
Content-Type: application/x-www-form-urlencoded

userId=T002&password=123456

# 人工判题相关接口

### 1. 获取待批改提交列表
POST http://localhost:8084/api/judge/pendinglist
Content-Type: application/json
satoken: b56578af-90db-4c72-abc4-a7c0ef83c806

{
  "practiceId": 1,
  "classId": 1
}

### 2. 获取提交详情
POST http://localhost:8084/api/judge/pending
Content-Type: application/json
satoken: b56578af-90db-4c72-abc4-a7c0ef83c806

{
  "submissionId": 3
}

### 3. 判题操作
POST http://localhost:8084/api/judge/judge
Content-Type: application/json
satoken: b56578af-90db-4c72-abc4-a7c0ef83c806

{
  "submissionId": 1,
  "questions": [
    {
      "sortOrder": 1,
      "score": 5,
      "maxScore": 10,
      "answerText": "class"
    },
    {
      "sortOrder": 2,
      "score": 3,
      "maxScore": 5,
      "comment": "true"
    }
  ]
}

# 提交练习相关接口

### 1. 提交练习答案
POST http://localhost:8084/api/submission/submit
Content-Type: application/json
satoken: b56578af-90db-4c72-abc4-a7c0ef83c806

{
  "practiceId": 1,
  "studentId": 1,
  "answers": [
      "public class Main { public static void main(String[] args) { System.out.println(\"Hello World\"); } }",
      "Java的面向对象特性包括封装、继承和多态。"
  ]
}
